name: "Build and populate cache"
on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '25 1 * * *'
jobs:
  build:
    strategy:
      matrix:
        nurRepo: [isabelroses]
        cachixName: [isabelroses]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v22
      with:
        install_url: https://releases.nixos.org/nix/nix-2.13.3/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          
    - name: Setup cachix
      uses: cachix/cachix-action@v12
      # Don't replace <YOUR_CACHIX_NAME> here!
      if: ${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}
      with:
        name: ${{ matrix.cachixName }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
  
    - name: Build packages
      run: |
        nix build -L .\#bellado
        nix build -L .\#catppuccin-hyprland
        nix build -L .\#catppuccinifier

    #- name: Trigger NUR update
    #  # Don't replace <YOUR_REPO_NAME> here!
    #  if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
    #  run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
